# Swagger??
# springdoc-openapi????
server:
  port: 8080
  servlet:
    context-path: /
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.example.loginmodule
# knife4j???????????????
knife4j:
  enable: true
  setting:
    language: zh_cn

#?????
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/database?serverTimezone=GMT%2b8
    username: root
    password: 1234

#??????
sender:
  email: #your 163email
  password: #your emailcode
mybatis:
  mapper-locations: classpath:mapper/**

#jedis??
jedis:
  host: 127.0.0.1
  port: 6379

#jwt??
jwt:
  secret: AbbeyRoad
  issuer: zhuang
  existHour: 2

